version: '3.4'

networks:
    backend:

services:
    petdb:
        container_name: pet-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Senha@123 
        networks:
            - backend
        ports:
            - 8001:1433
    petapi:
        container_name: pet-api
        image: ${DOCKER_REGISTRY-}petapi
        build:
            context: .
            dockerfile: Microservices/PetApi/PetApi/Dockerfile
        networks:
            - backend
        ports:
            - 8002:80
        environment:
            - DB_HOST=petdb
            - DB_NAME=db_pet
            - DB_SA_PASSWORD=Senha@123
